services:
  postgres:
    image: postgres:15
    container_name: aift-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - aift-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aift-redis

  backend:
    build:
      context: ./backend
      target: prod
    container_name: aift-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: aift-frontend
    depends_on:
      - backend

volumes:
  aift-postgres-data:

