"""${message}

Revision ID: ${down_revision}
Revises: ${up_revision}
Create Date: ${create_date}
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = ${repr(message)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

